site_name: 上海市南洋模范中学生存手册
site_url: http://127.0.0.1:8000/
site_author: 待风止浪息
repo_url: https://github.com/Uesugi-Erii-2024
repo_name: GitHub

nav: 
  - 主页: index.md

  - 基本信息:
    - 新生须知:
      - 日程表: articles/information/new_student/timetable/timetable.md
      - 晚自习: articles/information/new_student/self_study_at_night/self_study_at_night.md
      - 分班: articles/information/new_student/placement/placement.md
      - 班级工作: articles/information/new_student/committee/committee.md
      - 衣食住行:
        - 校服: articles/information/new_student/basic_necessities_of_life/uniform/uniform_2025.md
        - 食堂: articles/information/new_student/basic_necessities_of_life/canteen/canteen_2025.md
        - 宿舍: articles/information/new_student/basic_necessities_of_life/dormitory/dormitory_2025.md
        - 周边: articles/information/new_student/basic_necessities_of_life/surrounding_areas/surrounding_areas.md
      - 教师团队: articles/information/new_student/teachers/teachers.md
      - 名词解释: articles/information/new_student/glossary/glossary.md
    
    - 其他信息: articles/information/other_informations/other_informations.md


  - 校园活动:
    - 社团: /articles/activities/clubs.md
    - 东方绿洲: /articles/activities/oriental_land.md
    - 无锡研学: /articles/activities/wuxi.md
    - 团学联: /articles/activities/tuanxuelian.md
    - 军训: /articles/information/new_student/train/train.md
    - 学农: /articles/activities/farm.md
    - 艺术节: /articles/activities/art_festival.md
    - 科技节: /articles/activities/tech_festival.md
    - 职业体验: /articles/activities/job.md
    - 复旦卓越计划和交大学森计划: /articles/activities/fdjd_plan.md
    - 体育:
      - 南模杯: /articles/activities/nm_cup.md
      - 青峰杯: /articles/activities/qingfeng_cup.md
      - 运动会: /articles/activities/olympics.md




  - 学科攻略: 
    - 语文: 
      - 课内: articles/subjects/chinese/in_class/chinese_in_class.md
      - 竞赛: articles/subjects/chinese/competition/chinese_competition.md

    - 数学: 
      - 课内: articles/subjects/math/in_class/math_in_class.md
      - 竞赛: articles/subjects/math/competition/math_competition.md

    - 英语: 
      - 课内: articles/subjects/english/in_class/english_in_class.md
      - 竞赛: articles/subjects/english/competition/english_competition.md

    - 物理: 
      - 课内: articles/subjects/physics/in_class/physics_in_class.md
      - 竞赛: articles/subjects/physics/competition/physics_competition.md

    - 化学: 
      - 课内: articles/subjects/chemistry/in_class/chemistry_in_class.md
      - 竞赛: articles/subjects/chemistry/competition/chemistry_competition.md

    - 生物: 
      - 课内: articles/subjects/biology/in_class/biology_in_class.md
      - 竞赛: articles/subjects/biology/competition/biology_competition.md

    - 地理: 
      - 课内: articles/subjects/geography/in_class/geography_in_class.md
      - 竞赛: articles/subjects/geography/competition/geography_competition.md

    - 历史: 
      - 课内: articles/subjects/history/in_class/history_in_class.md

    - 政治: 
      - 课内: articles/subjects/politics/in_class/politics_in_class.md

    - 信息:  
      - 课内: articles/subjects/computer/in_class/computer_in_class.md
      - 竞赛: articles/subjects/computer/competition/computer_competition.md

  # - 美好瞬间:


  - Q&A: articles/information/other_informations/q_a.md




  - 关于我们: about_us.md

theme:
  name: material
  language: zh
  # features:
  #   - navigation.tabs
  palette:
    primary: light blue
  features:
    - header.autohide

extra_javascript:
  - js/gallery.js
  - js/timetable_loader.js

extra_css:
  - css/gallery.css
  - css/override-width.css

plugins:
  - search:
      lang:
          - en
          - ja
      separator: '[/s/-/.]+'
  
   
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Uesugi-Erii-2024
      name: auther